# @see: https://github.com/shivammathur/setup-php/blob/v2/examples/laravel-mysql.yml

name: Laravel CI

on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: 'Branch to run tests on'
        required: true
        default: main
        options:
          - main
  push:
    branches:
      - main
    paths:
      - '**.php'
      - 'composer.lock'
  pull_request:
    branches:
      - main
    paths:
      - '**.php'
      - 'composer.lock'

jobs:
  tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_ROOT_PASSWORD:
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}

    - name: Setup php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql
        coverage: none

    - name: Cache composer dependencies
      id: cache-composer
      uses: actions/cache@v3
      with:
        path: ./vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('./composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install composer dependencies
      if: steps.cache-composer.outputs.cache-hit != 'true'
      run: composer install -n --prefer-dist --no-scripts --no-progress

    - name: Dump composer autoload
      if: steps.cache-composer.outputs.cache-hit == 'true'
      run: composer dump-autoload

    - name: Copy .env
      run: cp .env.example .env

    - name: Generate key
      run: php artisan key:generate

    - name: Execute tests
      run: php artisan test
      env:
        DB_HOST: 127.0.0.1
